server {
    server_name bozheslav.ru www.bozheslav.ru;
    root /var/www/bozheslav/app/public;

    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/bozheslav.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/bozheslav.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.bozheslav.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = bozheslav.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name bozheslav.ru www.bozheslav.ru;
    return 404; # managed by Certbot




}